apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-server-2022
  labels:
    app: windows-server
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: windows-server-2022
    spec:
      domain:
        cpu:
          cores: 6
          sockets: 1
          threads: 1
        memory:
          guest: 12Gi
        resources:
          requests:
            memory: 12Gi
            cpu: "6"
          limits:
            memory: 12Gi
            cpu: "6"
        machine:
          type: q35
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: windows-server-2022-disk
